---
name: SCA Validation

on:
  pull_request:
    paths:
      - '.mvn/**'
      - 'src/**'
      - 'pom.xml'
      - '.classpath'
      - '.project'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sca:
    name: Validate Maven dependencies
    uses: bartoszbud/actions/.github/workflows/sast.yaml@main
    with:
      exit-code: 1 # fail the job if issues are found
      severity: LOW,MEDIUM,HIGH,CRITICAL
      ignore-unfixed: true
      format: table
      upload-artifact: true
      upload-release-assets: true
      upload-results-github-security: true